TOKEN_TYPE_BEARER = 'Bearer'
TOKEN_TYPE_BOT = 'Bot'

MESSAGE_POSITION_AROUND = 'around'
MESSAGE_POSITION_BEFORE = 'before'
MESSAGE_POSITION_ABOVE = 'above'
VALID_MESSAGE_POSITIONS = (MESSAGE_POSITION_AROUND, MESSAGE_POSITION_BEFORE, MESSAGE_POSITION_ABOVE)

EVENT_READY = 'READY'
EVENT_RESUMED = 'RESUMED'

EVENT_CHANNEL_CREATE = 'CHANNEL_CREATE'
EVENT_CHANNEL_UPDATE = 'CHANNEL_UPDATE'
EVENT_CHANNEL_DELETE = 'CHANNEL_DELETE'

EVENT_GUILD_CREATE = 'GUILD_CREATE'
EVENT_GUILD_UPDATE = 'GUILD_UPDATE'
EVENT_GUILD_DELETE = 'GUILD_DELETE'
EVENT_GUILD_BAN_ADD = 'GUILD_BAN_ADD'
EVENT_GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE'
EVENT_GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE'
EVENT_GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE'
EVENT_GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD'
EVENT_GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE'
EVENT_GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE'
EVENT_GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK'
EVENT_GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE'
EVENT_GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE'
EVENT_GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE'

EVENT_MESSAGE_CREATE = 'MESSAGE_CREATE'
EVENT_MESSAGE_UPDATE = 'MESSAGE_UPDATE'
EVENT_MESSAGE_DELETE = 'MESSAGE_DELETE'
EVENT_MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK'

EVENT_MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD'
EVENT_MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE'

EVENT_PRESENCE_UPDATE = 'PRESENCE_UPDATE'
EVENT_TYPING_START = 'TYPING_START'

EVENT_USER_SETTINGS_UPDATE = 'USER_SETTINGS_UPDATE'
EVENT_USER_UPDATE = 'USER_UPDATE'

EVENT_VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE'
EVENT_VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE'
